### ISSUE TITLE
Issue in installation with R 3.6 in Conda environment

### ISSUE THREAD

**Issue by darshanpandit** [Westat-Transportation/summarizeNHTS#9]
Hi. I am trying to install the package in my conda environment on an Archlinux machine.
The build tools is failing and following is the relevant stacktrace.

Could it be an Rtools issue? Conda has updated to R 3.6 and I saw some workarounds to get Rtools for 3.6.

Your help will be deeply appreciated.
I intend to call the methods via Rpy2 to export the data into Pandas dataframes.

```
cpp_helper_functions.cpp: In function 'double Rcpp_wgtmed(Rcpp::NumericVector, Rcpp::NumericVector)':
cpp_helper_functions.cpp:21:59: error: no matching function for call to 'make_pair<double, double>(Rcpp::traits::storage_type<14>::type&, Rcpp::traits::storage_type<14>::type&)'
     vals[i] = std::make_pair<double, double>(x[i], wgts[i]);
                                                           ^
In file included from /home/darshan/miniconda3/envs/nhts-env/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/utility:70:0,
                 from /home/darshan/miniconda3/envs/nhts-env/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/unordered_map:38,
                 from /home/darshan/miniconda3/envs/nhts-env/lib/R/library/Rcpp/include/Rcpp/platform/compiler.h:162,
                 from /home/darshan/miniconda3/envs/nhts-env/lib/R/library/Rcpp/include/Rcpp/r/headers.h:59,
                 from /home/darshan/miniconda3/envs/nhts-env/lib/R/library/Rcpp/include/RcppCommon.h:29,
                 from /home/darshan/miniconda3/envs/nhts-env/lib/R/library/Rcpp/include/Rcpp.h:27,
                 from cpp_helper_functions.cpp:1:
/home/darshan/miniconda3/envs/nhts-env/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/bits/stl_pair.h:519:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/home/darshan/miniconda3/envs/nhts-env/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/bits/stl_pair.h:519:5: note:   template argument deduction/substitution failed:
cpp_helper_functions.cpp:21:59: note:   cannot convert 'x.Rcpp::Vector<14, Rcpp::PreserveStorage>::operator[](((R_xlen_t)i))' (type 'Rcpp::traits::storage_type<14>::type {aka double}') to type 'double&&'
     vals[i] = std::make_pair<double, double>(x[i], wgts[i]);
                                                           ^
make: *** [/home/darshan/miniconda3/envs/nhts-env/lib/R/etc/Makeconf:175: cpp_helper_functions.o] Error 1
ERROR: compilation failed for package ‘summarizeNHTS’

```

**Comment by AnthonyFucci** [comment]
darshanpandit, I actually had not tested installing and using summarizeNHTS in a unix environment until now. I am able to confirm it works on Ubuntu 16.04 using install_github(), but I have no way to recreate your specific Conda environment. Your error suggests that the environment is using an unexpected or incompatible C++ library.

**Comment by marcelo-g-simas** [comment]
@AnthonyFucci I am seeing the same error when trying to install on MacOS (R 3.6) and RCpp version 1.0.4.6.  @afcates this may be something you can repro and test on your Mac.

**Comment by afcates** [comment]
No issues with installing on my Mac (R 3.5.0) - Rcpp version 1.0.4
I am going to upgrade to R 4.0, so I'll try again after that.

**Comment by afcates** [comment]
@darshanpandit @AnthonyFucci @Westat-Transportation 
Updated R to 4.0 and confirmed that I was getting the same error as above. 
Was able to get the package to build by removing `<double, double>` from: `vals[i] = std::make_pair<double, double>(x[i], wgts[i]);`

**Comment by darshanpandit** [comment]
Yes. I can confirm on this solution. [Here is the link](https://github.com/darshanpandit/summarizeNHTS/commit/4ea7123bc1ff917b596115a3d9268751a5372866) to my fix in a fork for the repository.
I forgot to report back on it back then, my apologies.
